# -*- coding: utf-8 -*-
"""AlyraFineTuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JFYfjHSIXpbUvJljE9QlSD0nFkvlJ9wp
"""

# !pip install -q unsloth
# !pip install -U transformers datasets accelerate peft trl bitsandbytes

from unsloth import FastLanguageModel

MAX_SEQ_LENGTH = 1024

BASE_MODEL = "Qwen/Qwen2.5-3B-Instruct"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name=BASE_MODEL,
    max_seq_length=MAX_SEQ_LENGTH,
    load_in_4bit=True,
    load_in_8bit=False,
    full_finetuning=False,
)

FastLanguageModel.for_inference(model)

print(f"\n[+] {BASE_MODEL} Model Loaded Successfully")

import torch
import json
import random
import math
import re
import os
from pathlib import Path

print("PyTorch:", torch.__version__)
print("CUDA available:", torch.cuda.is_available())
print("GPU:", torch.cuda.get_device_name(0))
print("VRAM:", round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2), "GB")

def generate_text(model, tokenizer, prompt):
    inputs = tokenizer(prompt,return_tensors="pt",truncation=True,max_length=1024).to(model.device)
    with torch.no_grad():
        outputs = model.generate(
            input_ids=inputs.input_ids,
            attention_mask=inputs.attention_mask,
            max_new_tokens=1024,
            do_sample=False,
            pad_token_id=tokenizer.eos_token_id
        )

    new_tokens = outputs[0, inputs.input_ids.shape[1]:]

    return tokenizer.decode(new_tokens,skip_special_tokens=True).strip()

#Converting json data to Dataset format after checking

from datasets import Dataset

def convert(path):
  with open(path,"r",encoding="utf-8") as f:
    dataset = json.load(f)

  formatted = []
  for sample in dataset:
    messages = [
    {
        "role":"user",
        "content":sample["instruction"] + "\n\n" + sample["input"]
    },
    {
        "role":"assistant",
        "content" : sample["output"]
    }]

    text = tokenizer.apply_chat_template(
        messages,
        tokenize=False,
        add_generation_prompt=False,
        enable_thinking=False,
        reasoning_effort="low"
    )
    formatted.append({
        "text":text
    })

  return Dataset.from_list(formatted)

training_dataset = convert("/content/train.json")
validation_dataset = convert("/content/validation.json")
test_dataset = convert("/content/test.json")

print("Train:", len(training_dataset))
print("Validation:", len(validation_dataset))
print("Test:", len(test_dataset))

print("\nSample:")
print(training_dataset[0]["text"])

#Finetuning code begins
SEED = 42
model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=[
        "q_proj",
        "k_proj",
        "v_proj",
        "o_proj",
        "gate_proj",
        "up_proj",
        "down_proj",
    ],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=SEED,
    use_rslora=True,
)

from unsloth.trainer import UnslothTrainer, UnslothTrainingArguments

training_args = UnslothTrainingArguments(
    output_dir="./alyraAI",

    num_train_epochs=2,
    per_device_train_batch_size=2,
    gradient_accumulation_steps=16,

    learning_rate=2e-4,
    warmup_ratio=0.03,
    lr_scheduler_type="cosine",

    optim="adamw_8bit",
    weight_decay=0.01,
    max_grad_norm=1.0,

    max_length=1024,
    packing=True,
    dataset_text_field="text",
    dataset_num_proc=2,

    eval_strategy="steps",
    eval_steps=100,
    per_device_eval_batch_size=2,

    save_strategy="steps",
    save_steps=100,
    save_total_limit=3,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",

    logging_steps=10,
    seed=SEED,
    report_to="none",
)

trainer = UnslothTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=training_dataset,
    eval_dataset=validation_dataset,
    args=training_args,
)

print("[OK] Trainer configured")
print(f"Train: {len(training_dataset):,} | Eval: {len(validation_dataset):,}")

#Finetuning Training Starts

print("[+]" * 20)
print("FINETUNING STARTED")
print("[+]" * 20)
print()

trainer_stats = trainer.train()

print("\n" + "[+]" * 20)
print("TRAINING COMPLETE")
print("[+]" * 20)
print(f"Final train loss: {trainer_stats.training_loss:.4f}")

from huggingface_hub import login

login()

HF_REPO = "OxOv3rH4uL/alyra-houseplan-qwen2.5-3b"
model.save_pretrained("./alyraAI")
tokenizer.save_pretrained("./alyraAI")

model.push_to_hub(HF_REPO)
tokenizer.push_to_hub(HF_REPO)

prompt = "Could you design me a house having a bedroom, kitchen, living room and toilet?"

res = generate_text(model,tokenizer,prompt)

print(res)